export const  FETCH_USER_PROFILE_BEGIN = "FETCH_USER_PROFILE_BEGIN";
export const  FETCH_USER_PROFILE_SUCESS = "FETCH_USER_PROFILE_SUCESS";
export const  FETCH_USER_PROFILE_FAILURE = "FETCH_USER_PROFILE_FAILURE";