export const  FETCH_USER_PROFILE_BEGIN = "FETCH_USER_PROFILE_BEGIN";
export const  FETCH_USER_PROFILE_SUCESS = "FETCH_USER_PROFILE_SUCESS";
export const  FETCH_USER_PROFILE_FAILURE = "FETCH_USER_PROFILE_FAILURE";

export const  FETCH_LANGUAGE_BEGIN =   "FETCH_LANGUAGE_BEGIN";
export const  FETCH_LANGUAGE_SUCESS =  "FETCH_LANGUAGE_SUCESS";
export const  FETCH_LANGUAGE_FAILURE = "FETCH_LANGUAGE_FAILURE";



